# -*- coding: utf-8 -*-
"""Train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uUZ-qMtscHIlw0zq_hZrwOEDWD5TEIT
"""

from google.colab import drive
drive.mount('data')

pip install pandas numpy opencv-python matplotlib

import pandas as pd
import os

extracted_folder = '/content/dataset'
csv_path = None

# 1. Automatically search for the driving_log.csv file
for root, dirs, files in os.walk(extracted_folder):
    if 'driving_log.csv' in files:
        csv_path = os.path.join(root, 'driving_log.csv')
        # Also capture the exact directory where the CSV was found
        # (The IMG folder is usually in the same directory as the CSV)
        base_dir = root
        break

if csv_path is None:
    raise FileNotFoundError("Could not find 'driving_log.csv' inside the extracted folder. Please check your zip file contents.")

print(f"Successfully found CSV at: {csv_path}")

# 2. Load the CSV
columns = ['center', 'left', 'right', 'steering', 'throttle', 'reverse', 'speed']
df = pd.read_csv(csv_path, names=columns)

# 3. Drop left and right camera columns
df = df[['center', 'steering']]

# 4. Fix file paths to point to your unzipped Colab directory
# The simulator saves paths like 'C:\...\IMG\center_2024.jpg'.
# We just extract the filename and append it to our local Colab IMG path.
img_folder_path = os.path.join(base_dir, 'IMG')
df['center'] = df['center'].apply(lambda x: os.path.join(img_folder_path, os.path.basename(x.strip().replace('\\', '/'))))

print("Dataset shape after dropping left/right cameras:", df.shape)
print(df.head())

import cv2
import numpy as np

def preprocess_image(image_path):
    # Read image using OpenCV
    img = cv2.imread(image_path)

    # Convert BGR (OpenCV default) to RGB
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Crop: remove top 60px (sky/scenery) and bottom 25px (car hood)
    img = img[60:135, :, :]

    # Resize to Nvidia CNN architecture standard (200x66)
    img = cv2.resize(img, (200, 66))

    # Normalize pixel values to [0.0, 1.0]
    img = img / 255.0
    return img

def augment_image(image_path, steering_angle):
    img = preprocess_image(image_path)

    # 50% chance to flip image horizontally to compensate for forward-only lap bias
    if np.random.rand() > 0.5:
        img = cv2.flip(img, 1)
        steering_angle = -steering_angle

    return img, steering_angle

# Test preprocessing on the first center image
test_img, test_steering = augment_image(df['center'].iloc[0], df['steering'].iloc[0])
print("Processed center image shape:", test_img.shape)

from sklearn.model_selection import train_test_split
import numpy as np

# Split data into 80% training and 20% validation sets
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

def batch_generator(dataframe, batch_size=32, is_training=True):
    num_samples = len(dataframe)
    while True: # Loop forever so the generator never terminates
        dataframe = dataframe.sample(frac=1).reset_index(drop=True) # Shuffle each epoch
        for offset in range(0, num_samples, batch_size):
            batch_samples = dataframe.iloc[offset:offset+batch_size]

            images = []
            angles = []

            for _, row in batch_samples.iterrows():
                path = row['center']
                angle = float(row['steering'])

                if is_training:
                    # Apply dynamic augmentation (flip) for training data
                    img, angle = augment_image(path, angle)
                else:
                    # Pure preprocessing for validation data
                    img = preprocess_image(path)

                images.append(img)
                angles.append(angle)

            X_batch = np.array(images)
            y_batch = np.array(angles)

            yield X_batch, y_batch

# Test generator
train_gen = batch_generator(train_df, batch_size=32, is_training=True)
val_gen = batch_generator(val_df, batch_size=32, is_training=False)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, Dropout

def build_nvidia_model():
    model = Sequential([
        # Convolutional Layers
        Conv2D(24, (5, 5), strides=(2, 2), activation='relu', input_shape=(66, 200, 3)),
        Conv2D(36, (5, 5), strides=(2, 2), activation='relu'),
        Conv2D(48, (5, 5), strides=(2, 2), activation='relu'),
        Conv2D(64, (3, 3), activation='relu'),
        Conv2D(64, (3, 3), activation='relu'),

        Dropout(0.5), # Helps prevent overfitting

        # Fully Connected Layers
        Flatten(),
        Dense(100, activation='relu'),
        Dense(50, activation='relu'),
        Dense(10, activation='relu'),
        Dense(1) # Predicts single continuous value: steering angle
    ])

    model.compile(optimizer='adam', loss='mse')
    return model

model = build_nvidia_model()
model.summary()

batch_size = 32
epochs = 10

steps_per_epoch = len(train_df) // batch_size
validation_steps = len(val_df) // batch_size

history = model.fit(
    train_gen,
    steps_per_epoch=steps_per_epoch,
    epochs=epochs,
    validation_data=val_gen,
    validation_steps=validation_steps,
    verbose=1
)

# Save the trained model file
model.save('model.h5')
print("Training complete! Saved trained model as model.h5")

from google.colab import files
files.download('model.h5')